project_id = "emlnkqygdkcngmftpsft"

[functions.generate-recurring-tasks]
verify_jwt = false

[functions.notify-user-created]
verify_jwt = false

[functions.notify-task-completed]
verify_jwt = false

[functions.notify-company-deactivated]
verify_jwt = false

[functions.notify-user-deleted]
verify_jwt = false

[functions.notify-user-deactivated]
verify_jwt = false

[functions.notify-user-reactivated]
verify_jwt = false

[functions.notify-meeting-created]
verify_jwt = false

[functions.create-whatsapp-instance]
verify_jwt = false

[functions.connect-whatsapp-instance]
verify_jwt = false

[functions.whatsapp-logs]
verify_jwt = false